export enum EvidenceType {
  CERTIFICATE = 'CERTIFICATE',
  PROJECT_LINK = 'PROJECT_LINK',
  ASSESSMENT = 'ASSESSMENT',
  WORK_HISTORY = 'WORK_HISTORY',
  TASK_COMPLETION = 'TASK_COMPLETION',
  OTHER = 'OTHER',
}